### ISSUE TITLE
Setup the dev environment pointing to trunk (2.23 DHIS2 version)

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/dhis2#1]

**Comment by ifoche** [comment]
@tokland , I've just shared with you a new DB. @josemp10 has generated it using Sierra Leone data from the DHIS2 demo server. We think it's better if you use Sierra Leone DB, as it contains aggregated data, to be able to play with pivot tables.

**Comment by tokland** [comment]
Setup done for 2.22. As we already discussed, 2.23-SNAPSHOT extracted some web-apps, including dhis-web-pivot, which makes the hot-reloading even more difficult. Until we know how to do it (the already asked the developers), I'll use 2.22. Btw, I found that:

https://blueprints.launchpad.net/dhis2/+spec/maven-app-portal-build

> Status as of 2.16:
> The improvement described below has been implemented as a maven-property useWarCompression={true|false} which enabled disabling of WAR file compression. This does drastically reduce build time in some cases and is implemented in 2.16. There should, however, be more possible improvements for a quicker build through streamlining the build/overlay process (maybe not use WARs altogether where applicable).

**Comment by tokland** [comment]
I'll upload here the 2.22 branch from bazaar. I'll keep the issue opened til then, the process is very long.

**Comment by ifoche** [comment]
@tokland 2.22 uploaded. Can you check that everything's ok?

**Comment by tokland** [comment]
It's ok, thx!
