### ISSUE TITLE
Migration from 2.22 to 2.23

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/dhis2#13]

**Comment by ifoche** [comment]
@tokland, DHIS2 developers have answered and their answer has been very clear (it was Jan who clarified the missing commands to finish the environment setup). Let me copy here his answer:

```
Hi guys,

You're close - just a couple of things.

d2-analysis has not been regularly published to npm as you don't want to do that all the time during development. It is way behind the git repo by now. So you need to link your local d2-analysis into the pivot app. Make sure you have git pulled d2-analysis and dhis2-pivot properly and then do:
- go to d2-analysis and type npm link (you might have to sudo all the commands below)
- go to dhis2-pivot/node_modules and clear out d2-analysis
- go to dhis2-pivot and type npm link d2-analysis

The pivot app now reads from your local d2-analysis instead of npm. Then
- go to d2-analysis and type (sudo) npm run build
- go to dhis2-pivot and type npm start

Go to localhost:8081 and it should load fine against your dhis2 backend at 8080.

Jan
```

**Comment by ifoche** [comment]
@tokland  By following Jan instructions from previous comment and executing a chrome without security (google-chrome --disable-web-security --user-data-dir=~) I finally got it working. There's also a CORS setting in DHIS, but I didn't managed to get it working by just adding http://localhost:8081 to that setting...so I think that for the moment we will need to use chrome without web security for the development

**Comment by tokland** [comment]
@ifoche: it worked! Just a minor problem: while changes in dhis2-web-pivot apply on a page reload, changes on dhis2-d2-analysis require a build (in d2-analysis + restart npm server on pivot). But for now it will do (probably there is a workaround for that).

Regarding the CORS, I was able to make it work adding "http://localhost:8081" to the setting you mentioned.

**Comment by ifoche** [comment]
just for the record: it's important not to put a final slash on the CORS URL setting (so avoid http://localhost:8081 <--- without final slash), otherwise it doesn't complain and it doesn't work

**Comment by tokland** [comment]
@ifoche: Can you create a fork for all the webapps we need to modify in 2.23? dhis-d2-analysis, dhis-web-pivot, dhis2-gis. Anything else?

**Comment by ifoche** [comment]
@tokland and what about creating a branch for the current state in each repo (something like "2.22") and continue there in master with the 2.23 code?

**Comment by tokland** [comment]
Do you mean copying all the webapps (we need to modify) directly on our repo dhis2 instead of having submodules?

**Comment by ifoche** [comment]
Sorry, I thought I had created already the forks from the beginning, but now I realize that we're pointing to their repos, my fault. Yes, of course, I create them now.

**Comment by tokland** [comment]
thx! I'll notify if we need more forks.

**Comment by ifoche** [comment]
done, I've moved the old repos to our forks and added the new dhis2-gis-api (37b967ee1b28b1ba4f31f2cba25c34e7654285e6)

do you think that these could be also interesting?
- [d2-ui](https://github.com/dhis2/d2-ui)
- [d2](https://github.com/dhis2/d2)

**Comment by tokland** [comment]
Not sure we'll need them, but won't hurt.

**Comment by tokland** [comment]
btw, the GIS repo we need is not the API but the webapp: https://github.com/dhis2/dhis2-gis

**Comment by ifoche** [comment]
sorry for that, I've created the fork for those 3 repos. Can you add them as submodules? (otherwise I can do it, but in a couple of hours)

**Comment by tokland** [comment]
No problem, done: 6662b280

**Comment by tokland** [comment]
Since they were doubts whether we need or not to add the "Legends" button to web-pivot, for now i've not done it. This ticket is ready for review.

**Comment by tokland** [comment]
Note that I've opened an issue upstream:

https://github.com/dhis2/d2-analysis/issues/2
