### ISSUE TITLE
Add new periods to all categories

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/dhis2#15]

**Comment by tokland** [comment]
PR done to all repos.

**Comment by tokland** [comment]
A comment. The "bi-month this year" option I added to the API/web-pivot works as expected, but with "weeks this year" I've found 2 problems:
- Values are either null or zero (that also happens with a vanilla 2.23, for example in play.dhis2.org/demo/)
- While "bi-months this year" are rendered correctly (from start of current year to end of year), weeks start at the current date (to one year from the current date). The code is the same that works for month/bimonth.

![web-pivot-weeks-bimonths-this-year](https://cloud.githubusercontent.com/assets/24643/15471990/25878792-20f9-11e6-8dce-e798064b6852.png)
