### ISSUE TITLE
Add 2 new periods to the pivot tables periods list

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/dhis2#2]

**Comment by ifoche** [comment]
- [ ] Months this calendar year
- [ ] Quarters this calendar year

**Comment by ifoche** [comment]
@tokland just in case you may want to check some API calls, I've just created the user in the development server for you. That way at least you will be able to check anything you may want to check before having your local DHIS2 development environment working.

**Comment by tokland** [comment]
About the translations: ar es fr lo pt ru tet tg vi. I can do some of them, but what about the others?

**Comment by ifoche** [comment]
Let's leave them with a simple google translation for the moment, and we'll review it later. Just a couple of questions here:
- Do you know how many terms are involved in the webapp? 
- Is the translation modularized by webapp or is there a big single po file for all the project?

**Comment by tokland** [comment]
Ok. For the record, the term used by dhis2 is "Months this year" and "Quarters this year", I'll keep them (unless we think it's too cryptic).
- dhis-web-pivot has 215 translatable terms.
- There is a file (i18n/i18n_app_LOCALE.properties) for each language. The format of those file is very simple: lines of `key=text` with unicode-escaping: https://github.com/EyeSeeTea/dhis2/blob/2.22/dhis-2/dhis-web/dhis-web-apps/src/main/webapp/dhis-web-pivot/i18n/i18n_app_es.properties

**Comment by ifoche** [comment]
ok, if thank you. If you think it will take too much time to add the translations, please just leave them in English. We'll talk to Oslo team and ask them how to proceed, because they  are using their own [Pootle server](http://translate.dhis2.net/) so probably they will want to translate it themselves whenever the code is accepted in their repo.

**Comment by tokland** [comment]
I already added the translations using Google Translate.

**Comment by ifoche** [comment]
perfect. Thank you!

**Comment by tokland** [comment]
e624e761
- Translated using Google Translate (except language "tet", I didn't found that code)
- Using the relative periods supported for the [API](http://dhis2.github.io/dhis2-docs/master/en/developer/html/ch01s04.html): `QUARTERS_THIS_YEAR` and `MONTHS_THIS_YEAR`.

![dhis-web-pivot-months-quarters](https://cloud.githubusercontent.com/assets/24643/14296584/1cc2f4be-fb7b-11e5-8f74-463f41124f3c.png)
![dhis-web-pivot-months-year](https://cloud.githubusercontent.com/assets/24643/14296585/1cc4a82c-fb7b-11e5-818e-3a93ff9d7011.png)
