### ISSUE TITLE
Include cumulative totals

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/dhis2#3]

**Comment by ifoche** [comment]
When total are displayed, introduce a new type of total that would be a "cummulative total", so it will show the sum of it's row/column plus the previous total, from the previous row/column

**Comment by tokland** [comment]
c6154f5
- New option: Options -> Show row cumulative totals. **Default=false.** Text translated only for those language that had already these family options translated (en, fr, vi)

![dhis-web-pivot-new-option](https://cloud.githubusercontent.com/assets/24643/14388760/e1da4442-fdaf-11e5-9705-0e9dca412788.png)
- Modified `scripts/table.js`, used in embedded tables:

![dhis-cumulative-embed](https://cloud.githubusercontent.com/assets/24643/14390966/c9fefb74-fdb9-11e5-8eff-cfa47adbc3eb.png)
- Modified `scripts/core.js`, use in the DHIS portal. 
  ![dhis-pivot-cumulative-portal](https://cloud.githubusercontent.com/assets/24643/14390981/d72ddfc2-fdb9-11e5-8753-4eb6e756a931.png)
- **IMPORTANT**: the new option `showRowCumulativeTotals` is not known by the API, so it's not persisted. When a favorite is loaded from DB, the flag will be disabled. Only when you enable the option, you see the new column. Embedded HTML are generated correctly. Files related for API:
  src/main/java/org/hisp/dhis/reporttable/ReportTable.java, /src/main/java/org/hisp/dhis/eventreport/EventReport.java.

**Comment by tokland** [comment]
I leave the ticket open till we decide what to do about the persistence of the option. We'll face the same problem at #4

**Comment by ifoche** [comment]
@tokland very good job. I think, as with the bkg color, it's better to go ahead with the rest of the activities and consider this done for the moment, so we will be able to come back here for the persistence of the option if we have time enough once the rest of the activities are done.

**Comment by josemp10** [comment]
@ifoche, @tokland, I know it has not been requested by the NRC, however, if
we are going to include this in the DHIS2 code, we have to consider also to
add the option "Show column cumulative totals". I mean, not now because we
need to talk to Oslo first, but it shouldn't be much time consuming task
right?

**Comment by ifoche** [comment]
Thanks @josemp10. We had already talked about it @tokland and I, and we already decided to continue working and leave it to the "second round", so not only we will be able to ask Oslo team, but also, we will see more tasks, and so more things to tell them and decide.

**Comment by tokland** [comment]
Created issue regardind the embed tables:
https://github.com/dhis2/d2-analysis/issues/1
