### ISSUE TITLE
Add right panel to indicators creation

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/dhis2#32]

**Comment by ifoche** [comment]
- [ ] In the current implementation, remove the second for loop that includes all the combinations in the first list
- [ ] Add to that right panel the dropdowns to select the attrb cat. combination
- [ ] Add an ok button to put the combination in the formula

**Comment by adrianq** [comment]
This task has been split into two different issues as there are important differences between 2.23 and 2.25.
- [Issue for 2.23](https://github.com/EyeSeeTea/maintenance-app/issues/1)
- [Issue for 2.25](https://github.com/EyeSeeTea/maintenance-app/issues/2)
