### ISSUE TITLE
Migrate NRC developments to 2.27

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dhis2#33]
- [x] Create 2.27 branch 
- [x] Migrate developments
   - [x] Add periods to pivot/charts
   - [x] Check how cumulative is done
   - [x] Check difference between what we did for the background colors and we currently have

**Comment by adrianq** [comment]
Dev server can be found at dev.eyeseetea.com:8080

**Comment by adrianq** [comment]
We are gonna be working in this repo: https://github.com/EyeSeeTea/dhis2-core

For the now, we are gonna implement periods and check the difference for the background colors.

**Comment by tokland** [comment]
- Added 4 periods to pivot/charts. Repos involved:

https://github.com/EyeSeeTea/dhis2-core/tree/feature/2.27-33-add-periods
https://github.com/EyeSeeTea/dhis2-visualizer/tree/feature/2.27-33-add-periods
https://github.com/EyeSeeTea/dhis2-pivot/tree/feature/2.27-33-add-periods
https://github.com/EyeSeeTea/d2-analysis/tree/feature/2.27-33-add-periods

Some Notes:

- PRs after the meeting tomorrow.

- English Translations: For now, I've only translated the English i18n file (I recall Nacho told me  they have translators).

- Webapps using  d2-analysis: The code for the periods lives in d2-analysis, but the translation is done by each webapp (why?). This forces us to translate those 4 new fields on every webapp. I have now done it for dhis2-visualizer and dhis2-pivot, but there are others (list may be incomplete). If not set, the text is empty (you only see the checkbox):

https://github.com/dhis2/dhis2-core-history
https://github.com/dhis2/dhis2-basicreport
https://github.com/dhis2/dhis2-core
https://github.com/dhis2/event-reports-app
https://github.com/dhis2/gis-app

- Weeks: If you run a request for the new period "Weeks This Year", you'll see that it starts at the current week, not the first week of the year. Also, the values rendered are always empty. Something seems amiss. We already saw this behaviour with 2.23. I've check the code and I arrived to WeeklyPeriodType.generatePeriods (https://github.com/dhis2/dhis2-core/blob/fb50a8c3c34ba5a27f30c9268bab9241aef3f15d/dhis-2/dhis-api/src/main/java/org/hisp/dhis/period/WeeklyPeriodType.java#L122). Compare it with MonthPeriodType.generatePeriods (https://github.com/dhis2/dhis2-core/blob/fb50a8c3c34ba5a27f30c9268bab9241aef3f15d/dhis-2/dhis-api/src/main/java/org/hisp/dhis/period/MonthlyPeriodType.java#L120). The former starts with the week, while the latter starts with the year. If I "fix" WeeklyPeriodType.generatePeriods to get weeks from the start of the week, then some other tests fails. So, for now, I've not committed those changes, I'll like to talk to Jose first.

**Comment by adrianq** [comment]
@adrianq to review:
- [x] Translations with @ifoche 
- [x] Strings are needed for these 3 repos?
https://github.com/dhis2/dhis2-core-history
https://github.com/dhis2/dhis2-basicreport
https://github.com/dhis2/dhis2-core
- [x] Discuss with Oslo about weeks

**Comment by tokland** [comment]
_Check how cumulative is done:_

Upstream JIRA Issue: https://jira.dhis2.org/browse/DHIS2-701

6 days ago, Edoardo said "implemented", but the only commit I see regarding cumulative adds the option:

https://github.com/dhis2/charts-app/commit/53bf092517d9fcf45f779250a4c521e478a33c6e

And it's indeed show, but it's not used anywhere (and the render does not change). I've asked what's the situation.

**Comment by tokland** [comment]
_Check difference between what we did for the background colors and we currently have_

Upstream JIRA Issue: https://jira.dhis2.org/browse/DHIS2-256

It's already working from 2.26. They did not add a new column as we did (bgcolor), instead they use the color from the legend set as background of the cell. The font color is automatically selected as black or white, depending on the background color.

There is _Legends_ button on pivot or gis apps, AFAIK you have to go to the legends app to configure it:

http://localhost:8080/dhis-web-maintenance/#/edit/otherSection/legendSet/

**Comment by tokland** [comment]
Add period translations for:

- https://github.com/dhis2/event-reports-app
I don't find this repo forked in EyeSeeTee.  Since I have no rights to create forks, I've done in my own fork for now: https://github.com/tokland/event-reports-app/tree/feature/2.27-33-add-periods

- https://github.com/dhis2/gis-app

AFICS, actually this webapp does not use those periods.

**Comment by adrianq** [comment]
@tokland Fork created:
https://github.com/EyeSeeTea/event-reports-app

For gis-app, we already had the fork created although it has a different name. 
https://github.com/EyeSeeTea/dhis2-gis

It should work, right?

**Comment by tokland** [comment]
@adrianq Can you check I have write rights for those repos?

$ git push --set-upstream origin feature/2.27-33-add-periods
ERROR: Permission to EyeSeeTea/event-reports-app.git denied to tokland.

**Comment by adrianq** [comment]
@tokland Yep, my fault. You should have it by now in event-reports

**Comment by tokland** [comment]
Cool, pushed.

By the way, I've cloned every repo in the dhis2 organization to try to guess which modules use the d2-analysis period tabs (WestRegionAggregateItems, WestRegionTrackerItems). Good news, I've only found the 3 we already had identified (event-resports, chats, pivot):

```
$ find -type f -name '*.js' | xargs -d"\n" -n10 grep '\.WestRegion\(Aggregate\|Tracker\)Items'
./event-reports-app/src/index.js:    var westRegionItems = uiManager.reg(ui.WestRegionTrackerItems(refs), 'accordion');
./charts-app/src/index.js:        westRegionItems: ui.WestRegionAggregateItems(refs),
./pivot-tables-app/src/index.js:        westRegionItems: ui.WestRegionAggregateItems(refs),
```

**Comment by adrianq** [comment]
@tokland Some notes about these tasks together with some feedback from Oslo:
- They are happy with the PRs we created and they agreed to merge them
- There is no need to create any other PR for any other repo. The other three repos are legacy repos or unused.
- No need to send translations for now
- What is already in core regarding cumulative and colors is enough. There is no need to modify any code or create any PR.
- The issue regarding weeks in pivot-table is not an issue :) When you are collecting data you define if you want to collect it by months, weeks or whatever. If you decide to collect it by months this is not going to be disaggregate per weeks or days as you don't know how to split the stored data. We were misunderstanding the behaviour.

I am closing this card as we have gone through everything. Anyway, we can further discuss everything during our meeting tomorrow. As usual, many thanks for the work. I am so happy you are on board! :)

**Comment by tokland** [comment]
> When you are collecting data you define if you want to collect it by months, weeks or whatever. If you decide to collect it by months this is not going to be disaggregate per weeks or days as you don't know how to split the stored data.

Cool, it makes sense.

The pleasure is all mine :)
