### ISSUE TITLE
Add conditional formatting to the cells background

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/dhis2#4]

**Comment by ifoche** [comment]
Even if the concept of conditional formatting, in principle, exists in the form of what DHIS2 call "legends" (as it was probably created for the map views), that only changes the font color, depending on the represented value. What we need here is to add, to those legends concept in DHIS, the capability of changing the background of a cell. 

Legends change both, the maps and the tables fonts, and here we would need to affect only the tables, what may add a little bit of complexity.

**Comment by tokland** [comment]
Added "Legends" button/dialog to web-pivot: 97e2a67

![dhis-web-pivot-legends](https://cloud.githubusercontent.com/assets/24643/14434523/7fa8ac76-0013-11e6-8581-0b7b4b091dde.png)

I've made no modifications regarding the new background attribute (until we decide about the persistence).

NOTE: Any create/update/delete on a legend requires a page reload to effectively see the change on the table or legend selection within options (style -> legend set). I've checked the behaviour of the web-app GIS and AFAICS, it works the same way. This does not mean it's impossible to do it, but it will require some time to refactor. Do do you think it's important enough to invest time on that?

**Comment by ifoche** [comment]
@tokland thank you very much, it looks perfect. Please go ahead with the persistence of the new background color attribute, as Oslo is not responding and that's something that can take a while to change...so let's go for a color background persistence in the legend table (maybe bkgcolor column?). I've asked @josemp10 and he didn't have an alternative way to do this without altering the DB. Regarding the page reload, as it's working in the same way for GIS, let's leave it like that, and if we have time enough, we will go back for it whenever the rest of the activities are done.

**Comment by josemp10** [comment]
@ifoche , @tokland just a quick comment. I know it makes much more sense to
have the legends as a part of the pivot menu as well, but for some reason
Oslo wanted to keep it only in the GIS menu (so till now, although the user
can use the legends in pivots or maps, the legends could be defined only in
the GIS). So, adding this (or not) to pivots is something that we may need
to discuss with them as well.

**Comment by josemp10** [comment]
Also, legends menu is a bit special, as it is not always being displayed to
the users (I am atthaching an image to demonstrate that, so it will be
better if you can read this ticket as an email?). It depends on the user
authorities, so only the superusers or the users with the 'Administrate
GIS' authority should be able to see the legends menu. Have you tested this
as well? Let me know if you need some help understanding this.

[image: Inline image 1]

**Comment by ifoche** [comment]
@josemp10, I thought we talked about this some weeks ago (regarding the position of the legends menu) and the conclusion was different, but however, we won't change it until you finally succeed in bringing Oslo guys to a meeting so we can ask them and be sure. Regarding the user permission to view the legends GIS, thanks for the advice. I think we will take a similar approach, we'll check it to view how is the behaviour now, but we'll continue working on the next tasks until the meeting with Oslo, so we can discuss with them this and more points that will come along the future tasks. Thanks for your comments.

**Comment by tokland** [comment]
@josemp10 Yes, I saw in the GIS code that the button was only shown for admin users (performs a request to `/api/me/authorization/F_GIS_ADMIN`). I replicated the same behaviour in pivot.

**Comment by tokland** [comment]
A minor issue: What do you think it's the best markup for the new background color selector? 

1) Add the color selector to the existing line (that's what I have now, see capture). Maybe changing text, but not plenty space to use. For example: "Symbolizer (fore/back)" 

2) Add a new row in the table (text: "Symbolizer (background)", for example).

![dhis-legends-set-symbolizer-color](https://cloud.githubusercontent.com/assets/24643/14533279/b57615fc-0264-11e6-969b-b44edf70add1.png)

**Comment by josemp10** [comment]
I would go for 2) ... It is what I think Oslo will prefer

**Comment by ifoche** [comment]
@tokland what would you feel more comfortable with as a user? Maybe we could add the text "foreground"/"background" to the selector leaving them as you have now and that would save a little space...However feel free to decide yourself if you find one solution more intuitive than another.

**Comment by tokland** [comment]
Note regarding the modification on the database: some frameworks provide a mechanism to describe the evolution of the DB. Apparently, dhis2 has no such mechanism and relies on manual modification of the schema. For example, I found that the upgrade notes start with a link to a SQL script that migrates the DB: https://www.dhis2.org/220-upgrade. Those scripts are stored at the repository https://github.com/dhis2/dhis2-utils. 

Until we decide where to store it, here is the SQL:

```
-- add-bgcolor-to-maplegends.sql
ALTER TABLE maplegend ADD COLUMN bgcolor character varying(255);
```

To be used:

```
$ psql -U dhis dhis2 < add-bgcolor-to-maplegends.sql
```

**Comment by tokland** [comment]
Al final lo he dejado de la segunda manera. Va captura.

![dhis-legend](https://cloud.githubusercontent.com/assets/24643/14611876/aecfa050-0594-11e6-92e4-e56dd418ea97.png)
